# Câ?u hi?nh ????ng dâ?n m??c ?i?nh
server:
  servlet:
    context-path: /api

# Kê?t nô?i database s?? du?ng mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/beprojectweb
    username: root
    password: Trandat123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
